### ISSUE TITLE
Filesize Limit?

### ISSUE THREAD

**Issue by WurstCommander** [mat-sz/filedrop-web#1] opened 2020-02-08 11:39 UTC
Hi,

very cool project. Is there a file size limit? a little PDF worked like a charm, a bigger .wave (I know old format :-) failed right after around 2-3 MB.

I read the README and found nothing about a size limit, sorry If I wasn't narrow enough with my research.

**Comment by mat-sz** [comment] 2020-02-08 11:43
There aren't any intentional file size limits, the only limits that would exist are bottlenecks caused by the browser, RAM or the TURN server I'm running.

I've just checked with a 16MB PDF file over TURN (home network connection to 4G phone connection) and it worked exactly like it should, except for the progress bar being broken.

Are you using the public instance (drop.lol)?

**Comment by WurstCommander** [comment] 2020-02-08 13:15
We are using drop.lol public

We are both on 16GB machines and this pdf worked:
![image](https://user-images.githubusercontent.com/5268576/74085764-e49b3b00-4a7c-11ea-8e43-f65e6793ac5c.png)

this random created 7z sadly not:
![image](https://user-images.githubusercontent.com/5268576/74085773-f846a180-4a7c-11ea-8468-41170045a4d7.png)

I have chrome and uBlock disabled.

Here a video clip: 
![tempfile_doesnwork](https://user-images.githubusercontent.com/5268576/74085823-6d19db80-4a7d-11ea-86ac-8e8fd6bb3688.gif)

**Comment by mat-sz** [comment] 2020-02-08 14:54
I can reproduce the problem on my end, let me see if there's anything I can do as this isn't what should be happening.

**Comment by mat-sz** [comment] 2020-02-09 18:50
So, this issue was pretty interesting to debug and fix.

I've fixed it going from Chrome/Firefox to Safari, but the reverse is not fixed yet (you can't send bigger files from Safari to other browsers yet). The reason for this issue is me blindly trusting in the `send` method on the RTCDataChannel and closing the channel prematurely. Unfortunately, the proper method for sending data (by relying on the `bufferedamountlow` event) doesn't work in Safari.

I'm working on a fix for Safari, meanwhile I've deployed the fix for other browsers to the production version.

To fix it on Safari, I would either:

* have to request the camera permission on drop.lol (won't happen because of the implications of such a message),
* manually check with the other party to the transfer at which offset it is (I prefer this option).

I will leave the issue open until everything works on Safari just fine, meanwhile enjoy the bigger transfers between Chrome/Firefox and any other combination of those two.

**Comment by mat-sz** [comment] 2020-02-13 20:44
Is the issue resolved?

**Comment by WurstCommander** [comment] 2020-02-14 22:27
hadn't a chance / time to test it again, I will try it soon and report back. Thank you for your help!

**Comment by WurstCommander** [comment] 2020-02-17 10:06
We tried again with a 2,5 GB file and it failed the same way. Transfer started, the connection stayed for around ~5 sec and then failed. Both used the newest chrome version 64 bit windows.

**Comment by mat-sz** [comment] 2020-12-15 10:43
@WurstCommander Took me a while, but it was an issue with me not understanding how WebRTC works. It's now fixed.

**Closed by mat-sz** 2020-12-15 10:43 UTC
Labels: bug
